# Generated by Django 4.2.23 on 2026-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_payment_new_expiration_date_alter_member_home_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertype',
            name='six_month_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membertype',
            name='six_month_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membertype',
            name='yearly_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membertype',
            name='yearly_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
