# Generated by Django 4.2.23 on 2026-03-29 13:30

from django.db import migrations

DISCOUNT_TYPES = ["Couple", "FarAway Friends", "Fixed/Income", "Regular", "Senior"]


def populate_discounts(apps, schema_editor):
    MemberType = apps.get_model("members", "MemberType")
    MemberType.objects.filter(member_type__in=DISCOUNT_TYPES).update(
        six_month_charge=5,
        six_month_duration=6,
        yearly_charge=10,
        yearly_duration=13,
    )


def reverse_discounts(apps, schema_editor):
    MemberType = apps.get_model("members", "MemberType")
    MemberType.objects.filter(member_type__in=DISCOUNT_TYPES).update(
        six_month_charge=None,
        six_month_duration=None,
        yearly_charge=None,
        yearly_duration=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_add_multiperiod_discount_fields"),
    ]

    operations = [
        migrations.RunPython(populate_discounts, reverse_discounts),
    ]
